AWSTemplateFormatVersion: 2010-09-09
Parameters:
  # S3 Parameters
  S3BucketName:
    Type: String
    Description: Name of S3 Bucket that will be created

  # CodeBuild Parameters
  GitHubRepo:
    Type: String
    Default: https://github.com/aleksandar-babic/vue-s3-demo
    Description: Github repository URL where SPA source code is located, default is https://github.com/aleksandar-babic/vue-s3-demo
  CodeBuildProjectName:
    Type: String
    Description: Name of CodeBuild project
  CodeBuildComputeType:
    Type: String
    Default: BUILD_GENERAL1_SMALL
    Description: Compute type for CodeBuild, default is BUILD_GENERAL1_SMALL
  CodeBuildEnvImage:
    Type: String
    Default: node:alpine
    Description: Environment image that will run in CodeBuild, default is node:alpine
  CodeBuildTimeout:
    Type: Number
    Default: 10
    Description: Timeout in mintues for CodeBuild, default is 10

  # ApiGateway/Lambda Parameters
  ApiGatewayStageName:
    Type: "String"
    Default: "v1"
    Description: Name of Api Gateway stage, default is v1
  LambdaFunctionName:
    Type: "String"
    Default: "fetch-data-function"
    Description: Name of Lambda function, default is fetch-data-function
  LambdaMemoryLimit:
    Type: Number
    Default: 128
    MinValue: 128
    MaxValue: 2048
    Description: Memory usage limit for lambda function, default is 128
  LambdaRuntime:
    Type: String
    Default: python2.7
    Description: Runtime that will Lambda function run in, default is python2.7
  LambdaTimeout:
    Type: Number
    Default: 10
    Description: Timeout in mintues for Lambda, default is 10
  LambdaSubnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of Subnets that will Lambda use
  LambdaS3Bucket:
    Type: String
    Default: rds-lambda-test-agt
    Description: Bucket name where deployment package is uploaded
  LambdaS3Key:
    Type: String
    Default: fetch-data-fn-deployment.zip
    Description: Key of deployment package on bucket

  # RDS Parameters
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VpcId of your existing Virtual Private Cloud (VPC)
    ConstraintDescription: must be the VPC Id of an existing Virtual Private Cloud.
  DBName:
    Default: AGTtest
    Description: The database name
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription:
      must begin with a letter and contain only alphanumeric
      characters.
  DBUser:
    NoEcho: 'true'
    Description: The database admin account username
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription:
      must begin with a letter and contain only alphanumeric
      characters.
  DBPassword:
    NoEcho: 'true'
    Description: The database admin account password
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.
  DBInstanceClass:
    Type: String
    Default: db.t2.small
    Description: Instance class of RDS
    AllowedValues:
      - db.t2.small
      - db.t3.small
      - db.t2.medium
      - db.t3.medium
    ConstraintDescription: must be a valid EC2 instance type.
  DBEngine:
    Type: String
    Default: mysql
    Description: Engine that will RDS instance run
    AllowedValues:
      - mysql
      - mariadb
      - aurora
      - aurora-mysql
  DBEngineVersion:
    Type: String
    Default: 5.6.40
    Description: Version of RDS engine
  RDSParamGroupFamily:
    Type: String
    Default: MySQL5.6
    Description: Parameter group family of RDS instance
  RDSSGCidr:
    Type: String
    Default: 0.0.0.0/0
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
    Description: CIDR notation access for RDS Security group

Outputs:
  S3BucketURL:
    Value: !GetAtt 
      - S3Bucket
      - WebsiteURL
    Description: URL for SPA hosted on S3

  S3BucketSecureURL:
    Value: !Join 
      - ''
      - - 'https://'
        - !GetAtt 
          - S3Bucket
          - DomainName
        - '/index.html'
    Description: Secure URL for SPA hosted on S3

  ApiGatewayInvokeURL:
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${ApiGatewayStageName}"
    Description: URL for API Gateway that will return RDS data

  RDSHostname:
    Value:
      !Join [
        '',
        [
          'RDS hostname: ',
          !GetAtt [RDS, Endpoint.Address],
          ':',
          !GetAtt [RDS, Endpoint.Port],
          /,
          !Ref 'DBName',
        ],
      ]
    Description: RDS DB Address and port    

Resources:
  # S3 Bucket setup
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: !Ref S3BucketName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
    DeletionPolicy: Retain

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: S3policy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref S3Bucket
                - /*
      Bucket: !Ref S3Bucket

  # Codebuild project setup
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub CodeBuildRole-${AWS::StackName}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "codebuild.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: /service-role/
      Policies:
        -
          PolicyName: "CodeBuildAccessPolicies"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*
              - 
                Effect: "Allow"
                Action:
                  - "s3:GetObject"
                  - "s3:GetObjectVersion"
                  - "s3:ListBucket"
                  - "s3:ListObjects"
                  - "s3:PutObject"
                  - "s3:PutObjectAcl"
                Resource: !Join 
                  - ''
                  - - 'arn:aws:s3:::'
                    - !Ref S3Bucket
                    - /*
                    
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref CodeBuildProjectName
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: !Ref CodeBuildComputeType
        Image: !Ref CodeBuildEnvImage
        EnvironmentVariables:
          -
            Name: S3_BUCKET_NAME
            Type: PLAINTEXT
            Value: !Ref S3BucketName
          -
            Name: VUE_APP_API_URL
            Type: PLAINTEXT
            Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${ApiGatewayStageName}"
      Source:
        Location: !Ref GitHubRepo
        Type: GITHUB
      Triggers:
        Webhook: true
      TimeoutInMinutes: !Ref CodeBuildTimeout
  
  # ApiGateway/Lambda setup
  ApiGateway:
    Type: "AWS::ApiGateway::RestApi"
    Properties:
      Name: "rds-lambda-api"
      Description: "API that will have method to return RDS data"

  ApiGatewayMethod:
    Type: "AWS::ApiGateway::Method"
    Properties:
      AuthorizationType: "NONE"
      HttpMethod: "GET"
      Integration:
        IntegrationHttpMethod: "POST"
        Type: "AWS_PROXY"
        Uri: !Sub
          - "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${lambdaArn}/invocations"
          - lambdaArn: !GetAtt "LambdaFunction.Arn"
      ResourceId: !GetAtt "ApiGateway.RootResourceId"
      RestApiId: !Ref "ApiGateway"

  ApiGatewayDeployment:
    Type: "AWS::ApiGateway::Deployment"
    DependsOn:
      - "ApiGatewayMethod"
    Properties:
      RestApiId: !Ref "ApiGateway"
      StageName: !Ref "ApiGatewayStageName"
    
  LambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket: !Ref LambdaS3Bucket
        S3Key: !Ref LambdaS3Key
      Description: "Function that will fetch RDS data and return as JSON"
      Environment:
        Variables:
           RDS_HOST: !GetAtt [RDS, Endpoint.Address]
           RDS_USER: !Ref DBUser
           RDS_PASSWORD: !Ref DBPassword
           RDS_DB: !Ref DBName
      FunctionName: !Ref "LambdaFunctionName"
      Handler: "index.handler"
      MemorySize: !Ref LambdaMemoryLimit
      Role: !GetAtt "LambdaIAMRole.Arn"
      Runtime: !Ref LambdaRuntime
      Timeout: !Ref LambdaTimeout
      VpcConfig:
        SecurityGroupIds: 
          - !Ref RDSSecurityGroup
        SubnetIds: !Ref LambdaSubnets

  LambdaApiGatewayInvoke:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !GetAtt "LambdaFunction.Arn"
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*/*/"

  LambdaIAMRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - "sts:AssumeRole"
            Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
      Policies:
        - PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Effect: "Allow"
                Resource:
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${LambdaFunctionName}:*"
          PolicyName: "lambda-logs"
        - PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                - "ec2:CreateNetworkInterface"
                - "ec2:DescribeNetworkInterfaces"
                - "ec2:DeleteNetworkInterface"
                Effect: "Allow"
                Resource:
                  - '*'
          PolicyName: "lambda-vpc"

  LambdaLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: !Sub "/aws/lambda/${LambdaFunctionName}"
      RetentionInDays: 90

  # RDS Setup
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG to allow internal access to RDS instance
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: !Ref RDSSGCidr
      VpcId:
        Ref: VpcId
  RDS:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Ref 'DBName'
      AllocatedStorage: '5'
      DBInstanceClass: !Ref DBInstanceClass
      Engine: !Ref DBEngine
      EngineVersion: !Ref DBEngineVersion
      MasterUsername: !Ref 'DBUser'
      MasterUserPassword: !Ref 'DBPassword'
      DBParameterGroupName: !Ref 'RDSParamGroup'
      PubliclyAccessible: false
      VPCSecurityGroups:
        - !Ref RDSSecurityGroup
  RDSParamGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Family: !Ref RDSParamGroupFamily
      Description: CloudFormation Database Parameter Group
      Parameters:
        autocommit: '1'
        general_log: '1'
        old_passwords: '0'